name: release-test
on:
  push:
    branches:
      - release-test
jobs:
  test-deployment:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Release to NPM
        run: cd release-config-test && npx semantic-release@19.0.5
